## 2.1.数据操作

In [1]:
import torch

In [20]:
print(f"cuda is available: {torch.cuda.is_available()}")

cuda is available: True


In [3]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x.shape

torch.Size([10])

In [6]:
x.numel()

10

In [8]:
X = x.reshape(2, 5)
X

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
ze = torch.zeros(2, 3, 4).to("cuda")
ze

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], device='cuda:0')

In [19]:
print(f"ze.shape: {ze.shape},\n ze.numel(): {ze.numel()} ,\n ze.dtype: {ze.dtype},\n ze.stride: {ze.stride()},\n ze.device: {ze.device}")

ze.shape: torch.Size([2, 3, 4]),
 ze.numel(): 24 ,
 ze.dtype: torch.float32,
 ze.stride: (12, 4, 1),
 ze.device: cuda:0


In [21]:
rn = torch.randn(2, 3, 4)
rn

tensor([[[-0.4837,  0.6917, -1.6434,  0.3789],
         [ 1.2346,  1.1762, -0.3939, -1.2434],
         [-0.5788,  0.2593,  0.0714, -1.1954]],

        [[-0.6129,  1.1229, -0.0905, -0.9458],
         [-0.5714, -0.9439, -1.0462, -0.6872],
         [-0.8182, -0.5809,  0.9205,  1.8853]]])

In [22]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [23]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [24]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [25]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [26]:
X.sum()

tensor(66.)

In [27]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [28]:
# 广播先扩展a，再扩展b,多出的为止为0,然后再加和
# a为(3,1),拓展为(3,2),再进行加和
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [29]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [30]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [31]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [32]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [33]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2438619866240
id(Z): 2438619866240


In [34]:
before = id(X)
X += Y
id(X) == before

True

In [35]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [36]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 练习

In [37]:
# 1.练习1
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
print(f"X==Y:{X==Y} \n X<Y:{X<Y} \n X>Y:{X>Y}")

X==Y:tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]]) 
 X<Y:tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]]) 
 X>Y:tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


In [38]:
# 2.练习2
a = torch.arange(12, dtype=torch.float32).reshape((3,4,1))
b = torch.arange(12, dtype=torch.float32).reshape((1,4,3))
a+b

tensor([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.],
         [ 8.,  9., 10.],
         [12., 13., 14.]],

        [[ 4.,  5.,  6.],
         [ 8.,  9., 10.],
         [12., 13., 14.],
         [16., 17., 18.]],

        [[ 8.,  9., 10.],
         [12., 13., 14.],
         [16., 17., 18.],
         [20., 21., 22.]]])