## 自定义层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(5.1223e-09, grad_fn=<MeanBackward0>)

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 6.6312e-01, -1.0931e+00, -1.8176e-03],
        [ 1.2517e+00, -4.7759e-03, -1.2195e+00],
        [-1.0028e+00, -5.6123e-01, -1.2577e+00],
        [-1.5047e+00,  2.3929e+00,  5.0803e-01],
        [ 1.6329e-01,  8.1249e-01, -2.5351e-01]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))

tensor([[1.3454, 0.4461, 0.0000],
        [1.4837, 0.0000, 0.0685]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])